### **Mathematical & Statistical Analysis for Data Science**

Task 1 – Linear Algebra Implementation

Dataset:
Linear Algebra Dataset:

In [1]:
import numpy as np
vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])
matrix_a = np.array([
[2, 1, 3],
[1, 0, 2],
[4, 1, 1]
])
matrix_b = np.array([
[1, 2, 0],
[3, 1, 4],
[2, 5, 1]
])

Using NumPy:
● Perform vector addition, subtraction, and dot product using vector_a and vector_b

In [2]:
vector_addition = vector_a + vector_b
print("Vector Addition:", vector_addition)

Vector Addition: [ 3  7 11]


In [3]:
vector_subtraction = vector_a - vector_b
print("Vector Subtraction:", vector_subtraction)

Vector Subtraction: [1 1 1]


In [4]:
dot_product = np.dot(vector_a, vector_b)
print("Dot Product:", dot_product)

Dot Product: 44


● Perform matrix addition and matrix multiplication using matrix_a and matrix_b

In [5]:
matrix_addition = matrix_a + matrix_b
print("Matrix Addition:\n", matrix_addition)

Matrix Addition:
 [[3 3 3]
 [4 1 6]
 [6 6 2]]


In [6]:
matrix_multiplication = np.dot(matrix_a, matrix_b)
print("Matrix Multiplication:\n", matrix_multiplication)

Matrix Multiplication:
 [[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]


● Calculate determinant of matrix_a

In [7]:
determinant = np.linalg.det(matrix_a)
print("Determinant of Matrix A:", determinant)

Determinant of Matrix A: 6.0


If determinant of matrix_a is not equal to zero, then find inverse of matrix_a

In [8]:
determinant = np.linalg.det(matrix_a)

if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix_a)
    print("Inverse of Matrix A:\n", inverse_matrix)
else:
    print("Matrix A does not have an inverse.")

Inverse of Matrix A:
 [[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]


● Compute eigenvalues and eigenvectors of matrix_a

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 5.54138127 -2.         -0.54138127]

Eigenvectors:
[[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


Another dataset

In [10]:
sales_success = [0.65, 0.35]
customer_segments = ["Premium", "Regular"]
segment_purchase_probability = {
"Premium": 0.80,
"Regular": 0.50
}

# **● Calculate probability of successful sales**

In [11]:
probability_success = (
    sales_success[0] * segment_purchase_probability["Premium"]
    + sales_success[1] * segment_purchase_probability["Regular"]
)

print("Probability of successful sales:", probability_success)
print("Percentage of successful sales:", probability_success * 100, "%")

Probability of successful sales: 0.6950000000000001
Percentage of successful sales: 69.5 %


## **Demonstrate conditional probability using customer segments**

In [12]:


sales_success = [0.65, 0.35]
customer_segments = ["Premium", "Regular"]

segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}

# Conditional probabilities
p_purchase_given_premium = segment_purchase_probability["Premium"]
p_purchase_given_regular = segment_purchase_probability["Regular"]

print("P(Purchase | Premium):", p_purchase_given_premium)
print("P(Purchase | Regular):", p_purchase_given_regular)

P(Purchase | Premium): 0.8
P(Purchase | Regular): 0.5


# **Data for Bayes’ theorem :**

In [13]:
# Probability Dataset for Customer Purchase Analysis
# P(A): Probability that a customer is Premium
P_A = 0.40
# P(B): Probability that a customer makes a purchase
P_B = 0.62
# P(B|A): Probability that a Premium customer makes a purchase
P_B_given_A = 0.80

Apply Bayes’ theorem to calculate updated probability of a customer purchase
○ Formula: P(A|B) = [P(B|A) * P(A)] / P(B)

In [14]:
# Given probabilities
P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80

# Bayes' theorem
P_A_given_B = (P_B_given_A * P_A) / P_B

print("P(A|B) =", P_A_given_B)
print("Probability =", P_A_given_B * 100, "%")

P(A|B) = 0.5161290322580646
Probability = 51.61290322580646 %


Data for Binomial distribution:

In [16]:
# Binomial Distribution Parameters - n = number of trials, p = probability of success
n_trials = 20
success_prob = 0.65

Simulate a binomial distribution for 20 trials

In [17]:
import numpy as np

# Binomial Distribution Parameters
n_trials = 20
success_prob = 0.65

# Simulate binomial distribution
binomial_data = np.random.binomial(
    n=n_trials,
    p=success_prob,
    size=1000
)

print("Simulated Binomial Distribution:")
print(binomial_data)

Simulated Binomial Distribution:
[13 13 15 14 14 15 10  9 13 14 14 10 13 14 12 13 10 14 14 15  8 10 13 11
 13 10 13 16 16  9 11 18 10 13 13 12 16 13 12 14  9 12 16 17 15 16 14 11
 10 12 16 12 12 13 11 14 15 15 12 13 15 12 18 10 15 14 14 12 11 15 10 12
 15 11 11 12 13 14 11  9  9 13 16 16 11 12 14 17 13 10 12 16 11 14 13 14
 15 14 10 11 13 14 17 13 16 16  9 13 14 12 14 13 11 15 10 13 13 15 11 17
 19 13 14 11 11 13 15 12 15 15 14 11 13  8 12 12 13 14 14 13 14 14 13 13
 13 16 11 12 16 17 10 19 15 14 15 15  9 11  7 16 11 16 14 14  9 11 12 14
 13 16 14 15 16 13 13 14  9 12 12 13 12 12 13 12 17 15 13 11 14 14 13 16
  9 13 20 14 16 10  9 16 13 13 11 11 14 11 15 13 12  8 17 15 13 14  8 10
 16 14 13 14 11  9 13  7 13 10 13  9 13 14 12 12 11 11 12 11 11 10 15 10
 11 15 13 15 15 13 12 13 14 13 15 13 13 13 15 12 11 12 13  8 14 13 17 12
 14 17 13 13 11 13 11 11 11 12 11 15 12 15 13 13 12 12 15 15 14 14 12  9
 15  9 16  6 17 14 12 14 15 14 13 14 15 13 16 11 10 12 15 12 10 10 13 13
 13 11 14 14 13 14

Data for this activity:

In [ ]:

# Distribution Parameters
normal_mean = 50
normal_std = 10
uniform_low = 0
uniform_high = 1

Generate a normal distribution and uniform distribution for the following parameters

In [15]:


# Distribution Parameters
normal_mean = 50
normal_std = 10

uniform_low = 0
uniform_high = 1

# Generate Normal Distribution
normal_data = np.random.normal(
    loc=normal_mean,
    scale=normal_std,
    size=1000
)

# Generate Uniform Distribution
uniform_data = np.random.uniform(
    low=uniform_low,
    high=uniform_high,
    size=1000
)

print("Normal Distribution:")
print(normal_data)

print("\nUniform Distribution:")
print(uniform_data)

Normal Distribution:
[57.64824687 49.25185214 68.14663541 49.37181817 46.08201864 61.64177907
 54.54400865 57.01855126 46.37842248 23.97031836 37.44996419 41.15803986
 43.11926589 51.3304147  62.29425881 40.45225503 45.88332049 51.03111822
 49.00810477 57.98499154 55.69655131 37.81095813 56.24159956 60.93955322
 58.39673789 65.32500892 43.80467582 60.49949047 46.01812917 47.42514207
 42.38587947 54.56292892 42.83841329 50.40043355 58.41913157 39.39213224
 41.93571555 32.08707345 41.41921748 40.35195193 39.50953237 57.81695645
 40.89728496 72.23545698 47.11522933 40.32827714 70.52078413 40.23121697
 61.47495377 46.55538513 43.0534243  69.15613445 40.2382692  62.93973188
 52.02933026 55.72294884 68.68136835 58.07943647 51.69882289 49.14698815
 33.32859404 53.55033438 52.77777691 55.02027944 50.94315554 55.46501229
 56.8739427  46.07576651 68.30293526 64.01007867 32.64835245 58.48925561
 56.42522312 55.25734116 27.5987164  47.97681808 42.31038442 39.84710014
 57.58590813 56.16837149 62.46

Task 3 – Descriptive Statistics
Statistical Dataset

In [18]:
sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

Compute mean, median, and mode of sales_data

In [19]:
import numpy as np
import pandas as pd
import statistics

sales_data = [
    120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
    190, 200, 210, 195, 185, 175, 165, 155, 145, 135
]

# Mean
mean = np.mean(sales_data)

# Median
median = np.median(sales_data)

# Mode
mode = statistics.mode(sales_data)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)

Mean: 165.5
Median: 165.0
Mode: 135


In [20]:
mode = statistics.multimode(sales_data)

print("Mode:", mode)

Mode: [135, 145, 155, 165, 175]


Calculate range, variance, and standard deviation

In [21]:
# Range
data_range = np.max(sales_data) - np.min(sales_data)

# Variance
variance = np.var(sales_data)

# Standard Deviation
standard_deviation = np.std(sales_data)

print("Range:", data_range)
print("Variance:", variance)
print("Standard Deviation:", standard_deviation)

Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356


Measure skewness and kurtosis

In [22]:
from scipy.stats import skew, kurtosis

skewness = skew(sales_data)
kurtosis_value = kurtosis(sales_data)

print("Skewness:", skewness)
print("Kurtosis:", kurtosis_value)

Skewness: 0.030143346252736614
Kurtosis: -0.7069943289224954


Interpret whether the dataset is symmetric, positively skewed, or negatively skewed

For this sales_data, the skewness is approximately 0.

Interpretation
Skewness ≈ 0

Therefore, the dataset is approximately symmetric.


Skewness > 0 → Positively (right) skewed
Skewness < 0 → Negatively (left) skewed
Skewness ≈ 0 → Symmetric

This data has:

Mean = 165
Median = 165
Skewness ≈ 0

Since the mean and median are equal and skewness is approximately zero, the sales distribution is symmetric.

Conclusion: ✅ The dataset is approximately symmetric, not positively or negatively skewed.